spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  password: sarath69kumar
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  hikari:
   maximum-pool-size: 20
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true