# LOCAL

spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  password: sarath69kumar
  url: jdbc:postgresql://localhost:5432/batchdemo
  username: postgres
  hikari:
   maximum-pool-size: 20
  #schema: batch
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
 batch: # Disable Auto-Run of Jobs on the Application Startup by setting enabled : false
  job:
   enabled: true
  jdbc:
   initialize-schema: ALWAYS
com.message: local application.yml
com.local.message: working in local lang