spring:
  profiles: # Check PropConfig.java
    active: dev,local # modify here to switch between environments. Always second value will be taken first
#    active: dev # Commet this line and uncomment above line to have two active profiles.
    include: application-${spring.profiles.active}.yml
    
server:
 port: 8086
 
# application file Profiling is bad way
com.message: Default application.yml
