spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  password: Reset@123
  url: jdbc:postgresql://172.16.1.112:5432/postgres
  username: postgres
  hikari:
   maximum-pool-size: 20
 jpa:
  hibernate:
   ddl-auto: update
  show-sql: true
 batch: # Disable Auto-Run of Jobs on the Application Startup
  job:
   enabled: false
com.message: dev application.yml